DROP TABLE IF EXISTS users;

CREATE TABLE users
(
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  enable TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);