DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
    id int(11) NOT NULL AUTO_INCREMENT,
    firstname varchar(100) NOT NULL,
    lastname varchar(100) NOT NULL,
    PRIMARY KEY (id)
);

-- Insert Users --
insert into USERS (firstname, lastname) values ('Sean', 'Louis');
insert into USERS (firstname, lastname) values ('Lori', 'Betty');
insert into USERS (firstname, lastname) values ('Bruce', 'Bruce');
insert into USERS (firstname, lastname) values ('Nancy', 'Jose');
insert into USERS (firstname, lastname) values ('Keith', 'Daniel');
insert into USERS (firstname, lastname) values ('Norma', 'Julia');
insert into USERS (firstname, lastname) values ('Daniel', 'Wanda');
insert into USERS (firstname, lastname) values ('Doris', 'Lisa');
insert into USERS (firstname, lastname) values ('Frances', 'Wayne');
insert into USERS (firstname, lastname) values ('Anthony', 'Juan');
insert into USERS (firstname, lastname) values ('Jack', 'John');
insert into USERS (firstname, lastname) values ('Alan', 'Harry');
insert into USERS (firstname, lastname) values ('Sharon', 'Marie');
insert into USERS (firstname, lastname) values ('Lillian', 'Antonio');
insert into USERS (firstname, lastname) values ('Jacqueline', 'Philip');
insert into USERS (firstname, lastname) values ('Jerry', 'John');
insert into USERS (firstname, lastname) values ('Ashley', 'Theresa');
insert into USERS (firstname, lastname) values ('Diane', 'Jean');
insert into USERS (firstname, lastname) values ('Lois', 'Louis');
insert into USERS (firstname, lastname) values ('Earl', 'Michael');
insert into USERS (firstname, lastname) values ('Jacqueline', 'Melissa');
insert into USERS (firstname, lastname) values ('Denise', 'Lisa');
insert into USERS (firstname, lastname) values ('Angela', 'Aaron');
insert into USERS (firstname, lastname) values ('Donald', 'Michael');
insert into USERS (firstname, lastname) values ('Joe', 'Tammy');
insert into USERS (firstname, lastname) values ('Nicholas', 'Ryan');
insert into USERS (firstname, lastname) values ('Russell', 'Albert');
insert into USERS (firstname, lastname) values ('Lois', 'Julie');
insert into USERS (firstname, lastname) values ('Carlos', 'Michael');
insert into USERS (firstname, lastname) values ('William', 'Dennis');
insert into USERS (firstname, lastname) values ('Harold', 'Harry');
insert into USERS (firstname, lastname) values ('Bonnie', 'Julie');
insert into USERS (firstname, lastname) values ('Jeffrey', 'Aaron');
insert into USERS (firstname, lastname) values ('Nicholas', 'Paul');
insert into USERS (firstname, lastname) values ('Wanda', 'Henry');
insert into USERS (firstname, lastname) values ('Deborah', 'Ann');
insert into USERS (firstname, lastname) values ('Aaron', 'Susan');
insert into USERS (firstname, lastname) values ('Alice', 'Alice');
insert into USERS (firstname, lastname) values ('Arthur', 'Scott');
insert into USERS (firstname, lastname) values ('Jose', 'Paul');
insert into USERS (firstname, lastname) values ('Shawn', 'Roy');
insert into USERS (firstname, lastname) values ('Stephanie', 'Henry');
insert into USERS (firstname, lastname) values ('Jeffrey', 'Christopher');
insert into USERS (firstname, lastname) values ('Deborah', 'Peter');
insert into USERS (firstname, lastname) values ('Linda', 'Mark');
insert into USERS (firstname, lastname) values ('Kevin', 'Lois');
insert into USERS (firstname, lastname) values ('Justin', 'Keith');
insert into USERS (firstname, lastname) values ('Kathleen', 'Benjamin');
insert into USERS (firstname, lastname) values ('Harold', 'Janet');
insert into USERS (firstname, lastname) values ('Andrew', 'Thomas');
insert into USERS (firstname, lastname) values ('Jesse', 'Willie');
insert into USERS (firstname, lastname) values ('Walter', 'Ruby');
insert into USERS (firstname, lastname) values ('Scott', 'David');
insert into USERS (firstname, lastname) values ('Jimmy', 'Phyllis');
insert into USERS (firstname, lastname) values ('Denise', 'Edward');
insert into USERS (firstname, lastname) values ('Teresa', 'Shawn');
insert into USERS (firstname, lastname) values ('Antonio', 'Samuel');
insert into USERS (firstname, lastname) values ('Rebecca', 'Jonathan');
insert into USERS (firstname, lastname) values ('Carlos', 'Arthur');
insert into USERS (firstname, lastname) values ('Jerry', 'Susan');
insert into USERS (firstname, lastname) values ('Paula', 'Carol');
insert into USERS (firstname, lastname) values ('Lori', 'Rebecca');
insert into USERS (firstname, lastname) values ('Jeffrey', 'Teresa');
insert into USERS (firstname, lastname) values ('John', 'Dorothy');
insert into USERS (firstname, lastname) values ('Randy', 'Carl');
insert into USERS (firstname, lastname) values ('Margaret', 'Benjamin');
insert into USERS (firstname, lastname) values ('Timothy', 'Katherine');
insert into USERS (firstname, lastname) values ('Earl', 'Gloria');
insert into USERS (firstname, lastname) values ('Craig', 'Phillip');
insert into USERS (firstname, lastname) values ('Chris', 'Jonathan');
insert into USERS (firstname, lastname) values ('Marie', 'Randy');
insert into USERS (firstname, lastname) values ('John', 'Anne');
insert into USERS (firstname, lastname) values ('Todd', 'Terry');
insert into USERS (firstname, lastname) values ('Clarence', 'Jason');
insert into USERS (firstname, lastname) values ('Shirley', 'Jennifer');
insert into USERS (firstname, lastname) values ('Norma', 'Mildred');
insert into USERS (firstname, lastname) values ('Lawrence', 'Wanda');
insert into USERS (firstname, lastname) values ('Jesse', 'Phillip');
insert into USERS (firstname, lastname) values ('Ashley', 'Jeffrey');
insert into USERS (firstname, lastname) values ('Kathy', 'Jason');
insert into USERS (firstname, lastname) values ('Roy', 'David');
insert into USERS (firstname, lastname) values ('Johnny', 'Wayne');
insert into USERS (firstname, lastname) values ('Chris', 'Elizabeth');
insert into USERS (firstname, lastname) values ('Charles', 'Peter');
insert into USERS (firstname, lastname) values ('Marilyn', 'Barbara');
insert into USERS (firstname, lastname) values ('Anthony', 'Phillip');
insert into USERS (firstname, lastname) values ('Dorothy', 'Randy');
insert into USERS (firstname, lastname) values ('Rose', 'Frances');
insert into USERS (firstname, lastname) values ('Mildred', 'Jose');
insert into USERS (firstname, lastname) values ('Carl', 'Cynthia');
insert into USERS (firstname, lastname) values ('Lillian', 'Kimberly');
insert into USERS (firstname, lastname) values ('Lawrence', 'Willie');
insert into USERS (firstname, lastname) values ('Sandra', 'Joan');
insert into USERS (firstname, lastname) values ('Phyllis', 'Sharon');
insert into USERS (firstname, lastname) values ('Andrew', 'Samuel');
insert into USERS (firstname, lastname) values ('Patricia', 'Charles');
insert into USERS (firstname, lastname) values ('Dorothy', 'Justin');
insert into USERS (firstname, lastname) values ('Edward', 'Janet');
insert into USERS (firstname, lastname) values ('Andrew', 'Stephanie');
insert into USERS (firstname, lastname) values ('Andrea', 'Barbara');