/**
 * Created by phompang on 3/30/2017 AD.
 */

export const CLEAR_POSTS = 'CLEAR_POSTS'
export const CLEAR_SINGLE_POST = 'CLEAR_SINGLE_POST'
export const CLEAR_USER_POSTS = 'CLEAR_USER_POSTS'

export const FETCH_USER = 'FETCH_USER'
export const SET_FULL_NAME = 'SET_FULL_NAME'
export const SET_DISPLAY_NAME = 'SET_DISPLAY_NAME'
export const SET_BIO = 'SET_BIO'

export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_SINGLE_POST = 'FETCH_SINGLE_POSTS'
export const FETCH_USER_POST = 'FETCH_USER_POST'
export const EDIT_CAPTION = 'EDIT_CAPTION'
export const DELETE_POST = 'DELETE_POST'

export const FETCH_COMMENT = 'FETCH_COMMENT'
export const ADD_COMMENT = 'ADD_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

export const FETCH_REACTION = 'FETCH_REACTION'
export const ADD_REACTION = 'ADD_REACTION'
export const EDIT_REACTION = 'EDIT_REACTION'
export const DELETE_REACTION = 'DELETE_REACTION'
